#!/bin/bash                                                                                                                                               
                                                                                                                                                       

cd /oasis/scratch/comet/oasselin/temp_project/leif/small_dipole/N2_1e-5_dt0.01/source/
cp /home/oasselin/leif/YBJ/*.f90 .
cd /oasis/scratch/comet/oasselin/temp_project/leif/small_dipole/N2_1e-5_dt0.01/output/
cp /home/oasselin/leif/YBJ/input_vort/*.dat .
cd /oasis/scratch/comet/oasselin/temp_project/leif/small_dipole/N2_1e-5_dt0.01/source/

PARA=parameters.f90
MAIN=main_waqg.f90
FFT=fft.f90
MPI=mpi.f90
INIT=init.f90
DERI=derivatives.f90
FILE=files.f90
DIAG=diagnostics.f90
ELLI=elliptic.f90
SPEC=special.f90


#Compile with MPIf90                                                                                                                                       
mpif90 -mkl parameters.f90 mpi.f90 fft.f90 files.f90 derivatives.f90 elliptic.f90 special.f90 diagnostics.f90 init.f90 main_waqg.f90 -o exec_full


